os: linux
sudo: false
dist: trusty

language: java
jdk: oraclejdk8

notifications:
  webhooks:
    urls:
      - "https://fleep.io/hook/Z0PU1GjzQUSGbrF3LPIIfg"
    on_success: always  # always|never|change
    on_failure: always
    on_start: always
    
cache:
    directories:
        - '$HOME/.m2/repository'

before_install:
    #NEEDED TO RUN THE GUI TESTS
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    
    
install: 
  # Resolve all dependencies
  - mvn --global-toolchains .travis.maven.toolchains.xml clean 
  #- travis_wait 60 mvn -B -q -V --global-toolchains .travis.maven.toolchains.xml -DskipTests compile

script:
  #- travis_wait 60 mvn -B -V -q --global-toolchains .travis.maven.toolchains.xml package jxr:aggregate site

after_success:
#DEPLOYMENT SCRIPTS
