os: linux
dist: trusty

language: java
jdk: oraclejdk8

env:
  global:
    - M2_MIRROR: '$HOME/m2_mirror'

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/m2_mirror'

before_install:
  - mvn --file build-tools/mirror-all clean package

install:
  - travis_wait 60 mvn --batch-mode --quiet --show-version --global-toolchains .travis.maven.toolchains.xml install

script:
  - travis_wait 60 mvn --batch-mode --quiet  --settings ./build-tools/settings.xml  --global-toolchains .travis.maven.toolchains.xml --file plugins/eclipse package  

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHN1bnllJTNBbWF0cml4Lm9yZy8lMjFPRkdWd3V4SnBuaGd5RkFGZ0UlM0FtYXRyaXgub3Jn"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
