os: linux
dist: trusty

language: java
jdk: oraclejdk8

env:
  global:
    - M2_MIRROR: '$HOME/m2_mirror'

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/m2_mirror'

before_install:
  - mvn --file modisco-tools/mirror-all clean package

install:
  - travis_wait 60 mvn --batch-mode --quiet --show-version --global-toolchains .travis.maven.toolchains.xml install

script:
  - travis_wait 60 mvn --batch-mode --quiet  --settings ./modisco-tools/settings.xml  --global-toolchains .travis.maven.toolchains.xml --file plugins/eclipse package  
