os: linux
sudo: false
dist: trusty

language: java
jdk: oraclejdk8

cache:
    directories:
        - '$HOME/.m2/repository'

before_script:
    #NEEDED TO RUN THE GUI TESTS
    - "echo 'Java Home:' $JAVA_HOME"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
    - mvn -B -V --global-toolchains .travis.maven.toolchains.xml install jxr:aggregate site

after_success:
#DEPLOYMENT SCRIPTS
