<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="methodcalls"
    nsURI="http://www.eclipse.org/MoDisco/MethodCalls/0.1.incubation/methodcalls"
    nsPrefix="methodcalls">
  <eClassifiers xsi:type="ecore:EClass" name="MethodCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//CallNode" eOpposite="#//CallNode/methodCalls"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callee" lowerBound="1"
        eType="#//CallNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteredSubMethods" upperBound="-1"
        eType="#//CallNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallsModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callNodes" upperBound="-1"
        eType="#//CallNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootNodes" upperBound="-1"
        eType="#//CallNode" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodCalls" upperBound="-1"
        eType="#//MethodCall" containment="true" eOpposite="#//MethodCall/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subMethods" upperBound="-1"
        eType="#//CallNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaMethod" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.java/model/java.ecore#//AbstractMethodDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
