/**$Id$
 * 
 * *******************************************************************************
 * Copyright (c) 2007 Politecnico di Milano, IST-034466 MOMOCS 
 * All rights reserved. This software and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     1. Matteo Miraz - Politecnico di Milano
 *     
 *******************************************************************************/

package org.eclipse.gmt.modisco.usecase.polimi.blog;

import javax.ejb.CreateException;
import javax.ejb.FinderException;
import javax.ejb.SessionBean;
import javax.ejb.SessionContext;
import javax.naming.Context;
import javax.naming.InitialContext;

import org.eclipse.gmt.modisco.usecase.polimi.auth.LoginSessionLocalHome;

/**
 *
 * @author matteo
 */
public class PostManagerSessionBean implements SessionBean {
    private LoginSessionLocalHome loginHome;
    private PostLocalHome postHome;
    
    private SessionContext context;
    
    // <editor-fold defaultstate="collapsed" desc="EJB infrastructure methods. Click the + sign on the left to edit the code.">;

    // TODO Add code to acquire and use other enterprise resources (DataSource, JMS, enterprise bean, Web services)
    // TODO Add business methods or web service operations

    /**
     * @see javax.ejb.SessionBean#setSessionContext(javax.ejb.SessionContext)
     */
    public void setSessionContext(SessionContext aContext) {
        context = aContext;
    }
    
    /**
     * @see javax.ejb.SessionBean#ejbActivate()
     */
    public void ejbActivate() {
        
    }
    
    /**
     * @see javax.ejb.SessionBean#ejbPassivate()
     */
    public void ejbPassivate() {
        
    }
    
    /**
     * @see javax.ejb.SessionBean#ejbRemove()
     */
    public void ejbRemove() {
        
    }
    
    // </editor-fold>;

    /**
     * See section 7.10.3 of the EJB 2.0 specification
     * See section 7.11.3 of the EJB 2.1 specification
     */
    public void ejbCreate() {
       
       try {
            
            Context initial = new InitialContext();
            
            this.postHome = (PostLocalHome) initial.lookup("java:comp/env/ejb/Post");
            this.loginHome = (LoginSessionLocalHome) initial.lookup("java:comp/env/ejb/LoginSession");
            
        } catch (Exception ex){
            ex.printStackTrace();
        }
        
    }

    public int post(String username, String password, String title, String body) {
        try {
            if (!this.loginHome.create().checkMail(username, password)) {
                return -1;
            }
        } catch (CreateException ex) {
            ex.printStackTrace();
            return -1;
        }
        PostLocal p;
        
        try {
            p = postHome.create(new Integer(0)); // this should be autogenerated
            
            p.setUsername(username);
            p.setTitle(title);
            p.setBody(body);

            return p.getId().intValue();
        } catch (CreateException ex) {
            ex.printStackTrace();
            return -1;
        }
    }

    public PostLocal checkPost(int postId) {
        try {
            return postHome.findByPrimaryKey(new Integer(postId));
        } catch (FinderException ex) {
            return null;
        }
    }
    
    // Add business logic below. (Right-click in editor and choose
    // "EJB Methods > Add Business Method" or "Web Service > Add Operation")
    
}
