<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smmquality"
    nsURI="http://www.eclipse.org/MoDisco/SMMQuality/0.9/smmquality" nsPrefix="smmquality">
  <eClassifiers xsi:type="ecore:EClass" name="QualityScope" eSuperTypes="platform:/plugin/org.eclipse.modisco.omg.smm/model/SMM-1.0.Beta2.ecore#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//QualityScope" eOpposite="#//QualityScope/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//QualityScope"
        eOpposite="#//QualityScope/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measurand" eSuperTypes="platform:/plugin/org.eclipse.modisco.omg.smm/model/SMM-1.0.Beta2.ecore#//AbstractMeasureElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
