<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="custom"
    nsURI="http://www.eclipse.org/MoDisco/infra/browser/custom/0.8" nsPrefix="uicustom">
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//TypeView" containment="true" eOpposite="#//TypeView/metamodelView"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allQuerySetsAvailable"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableQuerySets" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeView" eSuperTypes="#//CustomView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaclassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliesToSubInstances"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeView" containment="true" eOpposite="#//AttributeView/type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//ReferenceView" containment="true" eOpposite="#//ReferenceView/type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodelView" lowerBound="1"
        eType="#//MetamodelView" changeable="false" eOpposite="#//MetamodelView/types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeView" eSuperTypes="#//CustomView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TypeView"
        changeable="false" eOpposite="#//TypeView/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceView" eSuperTypes="#//CustomView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TypeView"
        changeable="false" eOpposite="#//TypeView/references"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomView" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customizedFeatures" upperBound="-1"
        eType="#//CustomViewFeature" containment="true" eOpposite="#//CustomViewFeature/customView"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomViewFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customizedFeature" eType="#//CustomizableFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueCases" upperBound="-1"
        eType="#//FeatureValueCase" containment="true" eOpposite="#//FeatureValueCase/feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//FeatureValue"
        containment="true" eOpposite="#//FeatureValue/feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customView" lowerBound="1"
        eType="#//CustomView" changeable="false" eOpposite="#//CustomView/customizedFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CustomizableFeatures">
    <eLiterals name="visible"/>
    <eLiterals name="label" value="1"/>
    <eLiterals name="fontName" value="2"/>
    <eLiterals name="color" value="3"/>
    <eLiterals name="backgroundColor" value="4"/>
    <eLiterals name="icon" value="5"/>
    <eLiterals name="bold" value="6"/>
    <eLiterals name="italic" value="7"/>
    <eLiterals name="underlined" value="8"/>
    <eLiterals name="struckthrough" value="9"/>
    <eLiterals name="hideMetaclassName" value="10"/>
    <eLiterals name="facetMainIcon" value="11" literal="facetMainIcon"/>
    <eLiterals name="facetOverlayIcon" value="12" literal="facetOverlayIcon"/>
    <eLiterals name="metaclassVisible" value="13" literal="metaclassVisible"/>
    <eLiterals name="collapseLink" value="14" literal="collapseLink"/>
    <eLiterals name="metaclassIcon" value="15" literal="metaclassIcon"/>
    <eLiterals name="instanceIcon" value="16" literal="instanceIcon"/>
    <eLiterals name="stickerIcon" value="17" literal="stickerIcon"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureValueCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//FeatureValue"
        containment="true" eOpposite="#//FeatureValue/case"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//CustomViewFeature" changeable="false" eOpposite="#//CustomViewFeature/valueCases"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.infra.query/model/query.ecore#//ModelQuery"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureValue" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//CustomViewFeature"
        changeable="false" eOpposite="#//CustomViewFeature/defaultValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" eType="#//FeatureValueCase"
        changeable="false" eOpposite="#//FeatureValueCase/value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticFeatureValue" eSuperTypes="#//FeatureValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedFeatureValue" eSuperTypes="#//FeatureValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueCalculator" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.gmt.modisco.infra.query/model/query.ecore#//ModelQuery"/>
  </eClassifiers>
</ecore:EPackage>
