<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelplex"
    nsURI="http://modelplex/1.0" nsPrefix="modelplex">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="To store informations of Modeplex discoveries."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModelplexDiscoverer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="It represents a discoverer chain, from source code to Uml model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toKdm" eType="#//ModelplexTransformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="link to root transformation from specific model to Kdm model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toUml" eType="#//ModelplexTransformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="link to root transformation from Kdm model to Uml model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DiscovererKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiscovererKind">
    <eLiterals name="csharp"/>
    <eLiterals name="java" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelplexTransformation" eSuperTypes="#//AtlTransformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="It represents root transformations in discoverer chain. These root transformations cannot being deselected, yet they are customizable."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="custom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="It indicates if it is the default root transformation or a customized one (if customized, a transformation path shall have been provided)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chainedTransformations"
        upperBound="-1" eType="#//AtlTransformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtlTransformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="It represents a transformation (using ATL technology)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="It indicates absolute path of transformation file (*.asm)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="To indicate if current transformation should be used in discoverer chain."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
