<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="internal" nsURI="http://www.eclipse.org/modisco/utils/chart/0.11.incubation/internal"
    nsPrefix="internal">
  <eSubpackages name="chart" nsURI="http://www.eclipse.org/modisco/utils/chart/0.11.incubation/internal/chart"
      nsPrefix="chart">
    <eClassifiers xsi:type="ecore:EClass" name="Chart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="axes" upperBound="-1"
          eType="#//chart/Axe" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="series" upperBound="-1"
          eType="#//chart/Serie" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Axe">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="legend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Serie">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
          eType="#//chart/Point" containment="true" eOpposite="#//chart/Point/serie"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Point">
      <eStructuralFeatures xsi:type="ecore:EReference" name="serie" lowerBound="1"
          eType="#//chart/Serie" eOpposite="#//chart/Serie/points"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coordinates" upperBound="-1"
          eType="#//chart/Coordinate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Coordinate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="axe" eType="#//chart/Axe"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
